import type { ThemeConfig } from 'ant-design-vue/es/config-provider/context';

export type YoThemeMode = 'console';

export const yoConsoleCssVars = {
  '--yo-font-family':
    '"Helvetica Neue", Helvetica, Arial, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
  '--yo-font-family-code': '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
  '--yo-font-size-1': '12px',
  '--yo-font-size-2': '14px',
  '--yo-font-size-3': '16px',
  '--yo-font-size-4': '18px',
  '--yo-font-size-5': '20px',
  '--yo-font-size-6': '24px',
  '--yo-font-size-7': '26px',
  '--yo-font-size-xs': 'var(--yo-font-size-1)',
  '--yo-font-size-sm': 'var(--yo-font-size-1)',
  '--yo-font-size-base': 'var(--yo-font-size-2)',
  '--yo-font-size-lg': 'var(--yo-font-size-3)',
  '--yo-font-size-title-sm': 'var(--yo-font-size-4)',
  '--yo-font-size-title-md': 'var(--yo-font-size-5)',
  '--yo-font-size-title-lg': 'var(--yo-font-size-6)',
  '--yo-font-size-title-xl': 'var(--yo-font-size-7)',
  '--yo-font-size-icon-lg': '21px',
  '--yo-font-size-icon-xl': '48px',
  '--yo-line-height-1': '14px',
  '--yo-line-height-2': '20px',
  '--yo-line-height-3': '24px',
  '--yo-line-height-4': '26px',
  '--yo-line-height-5': '28px',
  '--yo-line-height-6': '32px',
  '--yo-line-height-7': '36px',
  '--yo-line-height-xs': 'var(--yo-line-height-1)',
  '--yo-line-height-sm': 'var(--yo-line-height-1)',
  '--yo-line-height-base': 'var(--yo-line-height-2)',
  '--yo-line-height-lg': 'var(--yo-line-height-3)',
  '--yo-line-height-title-sm': 'var(--yo-line-height-4)',
  '--yo-line-height-title-md': 'var(--yo-line-height-5)',
  '--yo-line-height-title-lg': 'var(--yo-line-height-6)',
  '--yo-line-height-title-xl': 'var(--yo-line-height-7)',
  '--yo-font-weight-regular': '400',
  '--yo-font-weight-medium': '500',
  '--yo-font-weight-semibold': '600',
  '--yo-color-primary': '#3A7CFF',
  '--yo-color-primary-hover': '#5B92FF',
  '--yo-color-primary-active': '#2F63CC',
  '--yo-color-primary-bg': '#EBF2FF',
  '--yo-color-primary-bg-hover': '#F2F6FF',
  '--yo-color-success': '#22C070',
  '--yo-color-warning': '#FFA940',
  '--yo-color-error': '#E84A4A',
  '--yo-color-text-heading': '#313233',
  '--yo-color-text': '#626366',
  '--yo-color-text-secondary': '#939599',
  '--yo-color-text-tertiary': '#939599',
  '--yo-color-text-quaternary': '#C3C3C3',
  '--yo-color-text-placeholder': '#C3C3C3',
  '--yo-color-text-disabled': '#C3C3C3',
  '--yo-color-icon': '#626366',
  '--yo-color-icon-secondary': '#C3C3C3',
  '--yo-color-bg-layout': '#F7F8FA',
  '--yo-color-bg-container': '#ffffff',
  '--yo-color-bg-elevated': '#ffffff',
  '--yo-color-fill': '#F9FAFC',
  '--yo-color-fill-secondary': '#F5F6F7',
  '--yo-color-table-row-hover': '#F9FAFC',
  '--yo-color-disabled-bg': '#F5F6F7',
  '--yo-color-code-bg': '#101828',
  '--yo-color-code-panel': '#242932',
  '--yo-color-code-toolbar': '#283b4d',
  '--yo-color-code-text': '#e6edf7',
  '--yo-color-code-line-number': '#687386',
  '--yo-color-code-token-tag': '#f8d66d',
  '--yo-color-code-token-attr': '#ff7b91',
  '--yo-color-code-token-string': '#98d96f',
  '--yo-color-code-token-punctuation': '#aeb7c5',
  '--yo-color-code-token-keyword': '#7dd3fc',
  '--yo-color-code-token-function': '#fbbf24',
  '--yo-color-code-token-comment': '#778397',
  '--yo-color-warning-bg': '#fff7ed',
  '--yo-color-warning-border': '#fed7aa',
  '--yo-color-inline-code': '#c7254e',
  '--yo-color-inline-code-bg': '#fff5f7',
  '--yo-color-border': '#E6E8ED',
  '--yo-color-border-secondary': '#EDEFF2',
  '--yo-color-border-control': '#E6E8ED',
  '--yo-color-split': '#EDEFF2',
  '--yo-radius-xs': '2px',
  '--yo-radius-sm': '2px',
  '--yo-radius-base': '4px',
  '--yo-radius-lg': '8px',
  '--yo-control-height-sm': '28px',
  '--yo-control-height-base': '32px',
  '--yo-control-height-lg': '40px',
  '--yo-control-font-size-lg': '14px',
  '--yo-control-padding-inline-lg': '16px',
  '--yo-clear-icon-size': '16px',
  '--yo-button-icon-gap': '6px',
  '--yo-shadow-primary': '0 6px 14px rgba(58, 124, 255, 0.2)',
  '--yo-shadow-elevated': '0 8px 24px rgba(16, 24, 40, 0.08)',
} as const;

export const yoConsoleAntdTheme: ThemeConfig = {
  token: {
    colorPrimary: '#3A7CFF',
    colorInfo: '#3A7CFF',
    colorSuccess: '#22C070',
    colorWarning: '#FFA940',
    colorError: '#E84A4A',
    colorText: '#313233',
    colorTextHeading: '#313233',
    colorTextSecondary: '#626366',
    colorTextTertiary: '#939599',
    colorTextQuaternary: '#C3C3C3',
    colorTextDisabled: '#C3C3C3',
    colorBorder: '#E6E8ED',
    colorBorderSecondary: '#EDEFF2',
    colorSplit: '#EDEFF2',
    colorFillQuaternary: '#F9FAFC',
    colorFillTertiary: '#F5F6F7',
    colorBgLayout: '#F7F8FA',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    borderRadiusXS: 2,
    borderRadius: 4,
    borderRadiusSM: 2,
    borderRadiusLG: 8,
    fontFamily: yoConsoleCssVars['--yo-font-family'],
    fontWeightStrong: 600,
    fontSizeSM: 12,
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeXL: 20,
    fontSizeHeading1: 26,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 18,
    fontSizeHeading5: 16,
    lineHeight: 20 / 14,
    lineHeightSM: 14 / 12,
    lineHeightLG: 24 / 16,
    lineHeightHeading1: 36 / 26,
    lineHeightHeading2: 32 / 24,
    lineHeightHeading3: 28 / 20,
    lineHeightHeading4: 26 / 18,
    lineHeightHeading5: 24 / 16,
    controlHeight: 32,
    controlHeightSM: 28,
    controlHeightLG: 40,
  },
};

export const yoThemePresets: Record<YoThemeMode, ThemeConfig> = {
  console: yoConsoleAntdTheme,
};

export function mergeYoAntdTheme(baseTheme: ThemeConfig, customTheme?: ThemeConfig): ThemeConfig {
  if (!customTheme) {
    return baseTheme;
  }

  return {
    ...baseTheme,
    ...customTheme,
    token: {
      ...baseTheme.token,
      ...customTheme.token,
    },
    components: {
      ...baseTheme.components,
      ...customTheme.components,
    },
  };
}

export function getYoAntdTheme(themeMode: YoThemeMode, customTheme?: ThemeConfig): ThemeConfig {
  return mergeYoAntdTheme(yoThemePresets[themeMode], customTheme);
}
