import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

interface ComponentMeta {
  dirName: string;
  title: string;
  subtitle: string;
  group: string;
  order: number;
  docPath: string;
  demos: Array<{
    key: string;
    title: string;
    path: string;
  }>;
}

const currentDir = fileURLToPath(new URL('.', import.meta.url));
const rootDir = resolve(currentDir, '../../..');
const componentsDir = join(rootDir, 'packages/yostar-design/src/components');
const generatedDir = join(rootDir, 'apps/site/src/generated');
const generatedFile = join(generatedDir, 'routes.ts');

function toImportPath(fromFile: string, targetFile: string) {
  const fromDir = resolve(fromFile, '..');
  const raw = relative(fromDir, targetFile).split(sep).join('/');
  return raw.startsWith('.') ? raw : `./${raw}`;
}

function toDemoTitle(fileName: string) {
  const key = basename(fileName, '.vue');
  const titleMap: Record<string, string> = {
    basic: '基础用法',
    button: '按钮样式',
    option: 'Option 用法',
    group: '分组选项',
    nested: '内嵌选项',
    indeterminate: '半选状态',
    size: '尺寸展示',
    text: '文字开关',
    filter: '筛选样式',
    'search-clear': '搜索与清除',
    multiple: '多选模式',
    disabled: '禁用状态',
    status: '状态展示',
    icon: '图标用法',
    controls: '控制按钮',
    format: '格式化展示',
    formatter: '格式化展示',
    picker: '选择类型',
    'show-time': '日期时间',
    step: '步长选择',
    timezone: '时区展示',
    'options-scroll': '长列表滚动',
  };

  return titleMap[key] ?? key
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function getDemoOrder(fileName: string) {
  const key = basename(fileName, '.vue');
  const orderMap: Record<string, number> = {
    basic: 10,
    option: 15,
    group: 20,
    nested: 22,
    button: 25,
    indeterminate: 25,
    size: 30,
    text: 30,
    filter: 30,
    icon: 30,
    controls: 35,
    picker: 35,
    step: 35,
    'show-time': 40,
    format: 40,
    formatter: 40,
    timezone: 45,
    'search-clear': 40,
    'options-scroll': 45,
    multiple: 50,
    status: 60,
    disabled: 70,
  };

  return orderMap[key] ?? 100;
}

function readComponents() {
  if (!existsSync(componentsDir)) {
    return [];
  }

  return readdirSync(componentsDir, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map<ComponentMeta | null>(entry => {
      const componentDir = join(componentsDir, entry.name);
      const docPath = join(componentDir, 'index.zh-CN.md');

      if (!existsSync(docPath)) {
        return null;
      }

      const parsed = matter(readFileSync(docPath, 'utf-8'));
      const demoDir = join(componentDir, 'demo');
      const demos = existsSync(demoDir)
        ? readdirSync(demoDir)
            .filter(fileName => fileName.endsWith('.vue'))
            .sort((a, b) => getDemoOrder(a) - getDemoOrder(b) || a.localeCompare(b))
            .map(fileName => ({
              key: basename(fileName, '.vue'),
              title: toDemoTitle(fileName),
              path: join(demoDir, fileName),
            }))
        : [];

      return {
        dirName: entry.name,
        title: String(parsed.data.title ?? entry.name),
        subtitle: String(parsed.data.subtitle ?? ''),
        group: String(parsed.data.group ?? '组件'),
        order: Number(parsed.data.order ?? 100),
        docPath,
        demos,
      };
    })
    .filter((item): item is ComponentMeta => Boolean(item))
    .sort((a, b) => a.group.localeCompare(b.group, 'zh-CN') || a.order - b.order || a.title.localeCompare(b.title));
}

function generate() {
  const components = readComponents();
  mkdirSync(generatedDir, { recursive: true });

  const records = components.map(component => {
    const docImport = `${toImportPath(generatedFile, component.docPath)}?raw`;
    const demos = component.demos.map(demo => {
      const demoImport = toImportPath(generatedFile, demo.path);
      return `{
        key: ${JSON.stringify(demo.key)},
        title: ${JSON.stringify(demo.title)},
        component: () => import(${JSON.stringify(demoImport)}),
        source: () => import(${JSON.stringify(`${demoImport}?raw`)}),
      }`;
    });

    return `{
      name: ${JSON.stringify(component.dirName)},
      path: ${JSON.stringify(`/components/${component.dirName}`)},
      title: ${JSON.stringify(component.title)},
      subtitle: ${JSON.stringify(component.subtitle)},
      group: ${JSON.stringify(component.group)},
      order: ${component.order},
      doc: () => import(${JSON.stringify(docImport)}),
      demos: [${demos.join(',')}],
    }`;
  });

  const content = `/* This file is generated by apps/site/scripts/generate-routes.ts. */

export interface DemoRecord {
  key: string;
  title: string;
  component: () => Promise<unknown>;
  source: () => Promise<unknown>;
}

export interface ComponentRouteRecord {
  name: string;
  path: string;
  title: string;
  subtitle: string;
  group: string;
  order: number;
  doc: () => Promise<unknown>;
  demos: DemoRecord[];
}

export const componentRoutes: ComponentRouteRecord[] = [${records.join(',')}];
`;

  writeFileSync(generatedFile, content);
  console.log(`Generated ${components.length} component route(s).`);
}

generate();
